@baseUrl=http://localhost:3333/api
@eventId={{createEvent.response.body.eventId}}
@subscriptionId={{subscribeToEvent.response.body.subscriptionId}}

# @name createEvent

POST {{baseUrl}}/events 
Content-Type: application/json

{
    "name": "Event 2",
    "description": "Event 1 description",
    "date": "2025-04-12"
}

### 

# @name subscribeToEvent

POST {{baseUrl}}/events/{{eventId}}/subscribe
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe2@gmail.com"
}

###

# @name cancelToEvent

DELETE {{baseUrl}}/subscriptions/{{subscriptionId}}


